import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const html = await fs.readFile(new URL('../index.html', import.meta.url), 'utf8');
const app = await fs.readFile(new URL('../app.js', import.meta.url), 'utf8');
const engine = await fs.readFile(new URL('../catalog-engine.js', import.meta.url), 'utf8');
const ids = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]));
const requested = [...app.matchAll(/\$\("([^"]+)"\)/g)].map(m => m[1]);
for (const id of requested) assert(ids.has(id), `Falta el elemento #${id} usado por app.js`);
assert.match(html, /v1\.0\.0/);
assert.match(engine, /const VERSION = "1\.0\.0"/);
assert.match(app, /WatiCatalogEngine/);
assert(ids.has('export-languages'));
assert(ids.has('primary-locale'));
assert(ids.has('preview-locale'));
assert(ids.has('name-source-filter'));
assert(ids.has('generated-name-warning'));
assert.match(app, /nameOverrides/);
assert.match(app, /es_MX/);
assert.match(app, /en_US/);
console.log(`UI estática aprobada: ${ids.size} IDs y ${requested.length} referencias verificadas.`);
